### ISSUE TITLE
Pod install failing v0.12.0 with Cocoapods 1.11.3

### ISSUE THREAD

**Issue by albertovelazmoliner** [tokenstreet-tech/react-native-idnow-videoident#627]
**Describe the bug**
Running `pod install` is not working

**To Reproduce**

1. yarn install
2. cd examples/bare
3. yarn install
4. cd ios
5. pod install

**Expected behavior**
Install pod dependencies

**Screenshots**

### Error

```
LoadError - dlopen(/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (no such file), '/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) - /Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `require'
/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/Users/alberto.moliner/.rvm/rubies/ruby-2.7.5/lib/ruby/gems/2.7.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `require'
...
```

**Smartphone (please complete the following information):**
-  Version [0.12.0]

**Additional context**
- Ruby 2.7.5
- M1 Pro processor
- cocoapods-1.11.3
- macOS: 13.0.1 (22A400)

**Comment by albertovelazmoliner** [comment]
After running this:
```
    sudo arch -arm64e gem install cocoapods
    sudo arch -arm64e gem install ffi
```

It worked fine. Sorry for the issue 🤦🏼‍♂️
